package com.example.andro25

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.TextView
import android.widget.Toast
import com.example.andro25.databinding.ActivityMainBinding
import com.example.andro25.util.checkDecoding
import com.example.andro25.util.hexToString
import com.example.andro25.util.stringToHex

class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.i(TAG, "Hello from Kotlin")

        val init = initRng()
        Log.i(TAG, "Initialisation of RNG status code: $init")

        val bytes = randomBytes(10)
        Log.i(TAG, "Randomly generated bytearray status: ${if (bytes.isEmpty()) "not generated" else "generated"}")

        val key = randomBytes(16)
        val data = randomBytes(35)
        val encryptedData = encrypt(key, data)
        Log.i(TAG, "Data encrypted ${if (encryptedData.isEmpty()) "unsuccessfully" else "successfully"}")

        val decryptedData = decrypt(key, encryptedData)
        val result = checkDecoding(data, decryptedData)
        Log.i(TAG, "Data decrypted ${if (result) "successfully" else "unsuccessfully"}")




        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Example of a call to a native method
        binding.sampleText.text = stringFromJNI()
    }

    external fun stringFromJNI(): String
    external fun initRng(): Int
    external fun randomBytes(no: Int): ByteArray
    external fun encrypt(key: ByteArray, data: ByteArray): ByteArray

    external fun decrypt(key: ByteArray, data: ByteArray): ByteArray


    companion object {
        private const val TAG = "MainActivity"
        init {
            System.loadLibrary("mbedcrypto")
            System.loadLibrary("andro25")
            Log.i(TAG, "Libraries loaded successfully")
        }
    }

}