package com.example.andro25

import android.app.Activity
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.TextView
import android.widget.Toast
import androidx.activity.result.ActivityResult
import androidx.activity.result.ActivityResultCallback
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.result.registerForActivityResult
import com.example.andro25.databinding.ActivityMainBinding
import com.example.andro25.nativelibs.NativeLib
import com.example.andro25.nativelibs.NativeLib.decrypt
import com.example.andro25.nativelibs.NativeLib.encrypt
import com.example.andro25.nativelibs.NativeLib.initRng
import com.example.andro25.nativelibs.NativeLib.randomBytes
import com.example.andro25.util.checkDecoding
import com.example.andro25.util.hexToString
import com.example.andro25.util.stringToHex

class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding
    private lateinit var activityResultLauncher: ActivityResultLauncher<Intent>


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.i(TAG, "Hello from Kotlin")

        activityResultLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()
        ) { result: ActivityResult ->
            if (result.resultCode == RESULT_OK) {
                val data = result.data
                val pin = data?.getStringExtra("pin")
                Toast.makeText(this, pin, Toast.LENGTH_SHORT).show()
            }
        }

        val init = initRng()
        Log.i(TAG, "Initialisation of RNG status code: $init")

        val bytes = randomBytes(10)
        Log.i(TAG, "Randomly generated bytearray status: ${if (bytes.isEmpty()) "not generated" else "generated"}")

        val key = randomBytes(16)
        val data = randomBytes(35)
        val encryptedData = encrypt(key, data)
        Log.i(TAG, "Data encrypted ${if (encryptedData.isEmpty()) "unsuccessfully" else "successfully"}")

        val decryptedData = decrypt(key, encryptedData)
        val result = checkDecoding(data, decryptedData)
        Log.i(TAG, "Data decrypted ${if (result) "successfully" else "unsuccessfully"}")





        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Example of a call to a native method
        //binding.sampleText.text = stringFromJNI()
    }

    fun onActivityResult(result: ActivityResult){

    }



    fun onButtonClick(v: View){
//        val key = randomBytes(16)
//        val data = stringToHex("010AFD00458395867BC3")
//        val encrypted = encrypt(key, data)
//        val decrypted = decrypt(key, encrypted)
//        val s = hexToString(decrypted)
//
//        Toast.makeText(this, s, Toast.LENGTH_SHORT).show()

        val it = Intent(this, PinpadActivity::class.java)
        activityResultLauncher.launch(it)
    }



    companion object {
        private const val TAG = "MainActivity"

    }

}