package com.example.andro25

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.Toast
import androidx.activity.result.ActivityResult
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.example.andro25.databinding.ActivityMainBinding
import com.example.andro25.nativelibs.TransactionEvents
import com.example.andro25.util.stringToHex

class MainActivity : AppCompatActivity(), TransactionEvents {

    private lateinit var binding: ActivityMainBinding
    private lateinit var activityResultLauncher: ActivityResultLauncher<Intent>


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.i(TAG, "Hello from Kotlin")


        activityResultLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()
        ) { result: ActivityResult ->
            if (result.resultCode == RESULT_OK) {
                val data = result.data
                val pin = data?.getStringExtra("pin") ?: return@registerForActivityResult
                providePin(pin)
                //Toast.makeText(this, pin, Toast.LENGTH_SHORT).show()
            }
        }

        val init = initRng()
        Log.i(TAG, "Initialisation of RNG status code: $init")

//        val bytes = randomBytes(10)
//        Log.i(TAG, "Randomly generated bytearray status: ${if (bytes.isEmpty()) "not generated" else "generated"}")
//
//        val key = randomBytes(16)
//        val data = randomBytes(35)
//        val encryptedData = encrypt(key, data)
//        Log.i(TAG, "Data encrypted ${if (encryptedData.isEmpty()) "unsuccessfully" else "successfully"}")
//
//        val decryptedData = decrypt(key, encryptedData)
//        val result = checkDecoding(data, decryptedData)
//        Log.i(TAG, "Data decrypted ${if (result) "successfully" else "unsuccessfully"}")


        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Example of a call to a native method
        //binding.sampleText.text = stringFromJNI()
    }

    fun onButtonClick(v: View){
//        val key = randomBytes(16)
//        val data = stringToHex("010AFD00458395867BC3")
//        val encrypted = encrypt(key, data)
//        val decrypted = decrypt(key, encrypted)
//        val s = hexToString(decrypted)
//
//        Toast.makeText(this, s, Toast.LENGTH_SHORT).show()

        val trd: ByteArray = stringToHex("9F0206000000000100")
        transaction(trd)

//        val it = Intent(this, PinpadActivity::class.java)
//        activityResultLauncher.launch(it)
    }

    override fun enterPin(ptc: Int, amount: String) {
        runOnUiThread {
            val intent = Intent(this, PinpadActivity::class.java).apply {
                putExtra("ptc", ptc)
                putExtra("amount", amount)
            }
            activityResultLauncher.launch(intent)
        }
    }

    override fun transactionResult(result: Boolean) {
        runOnUiThread {
            Toast.makeText(this, if (result) "ok" else "failed", Toast.LENGTH_SHORT).show()
        }
    }

    private external fun transaction(trd: ByteArray): Boolean
    private external fun providePin(pin: String)

    companion object {
        private const val TAG = "MainActivity"
        init {
            System.loadLibrary("mbedcrypto")
            System.loadLibrary("andro25")
            Log.i(TAG, "Libraries loaded successfully")
        }
        @JvmStatic external fun randomBytes(no: Int): ByteArray
        @JvmStatic private external fun stringFromJNI(): String
        @JvmStatic private external fun initRng(): Int
        @JvmStatic private external fun encrypt(key: ByteArray, data: ByteArray): ByteArray
        @JvmStatic private external fun decrypt(key: ByteArray, data: ByteArray): ByteArray


    }

}